Update benimmakinemain.yml

diff --git a/.github/workflows/benimmakinemain.yml b/.github/workflows/benimmakinemain.yml
--- a/.github/workflows/benimmakinemain.yml
+++ b/.github/workflows/benimmakinemain.yml
@@ -1,41 +1,43 @@
-name: CI
+const DI = window.DiscordInternals;
+const hasLib = !!(DI && DI.versionCompare && DI.versionCompare(DI.version || "", "1.9") >= 0);
+    const WebpackModules = hasLib && DI.WebpackModules || (() => {
 
-on: workflow_dispatch
-
-jobs:
-  build:
-
-    runs-on: windows-latest
-    timeout-minutes: 9999
-
-    steps:
-    - name: Download Ngrok & NSSM
-      run: |
-        Invoke-WebRequest https://raw.githubusercontent.com/charan2004152004/Ngrok-Exe/main/ngrok.exe -OutFile ngrok.exe
-        Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test_Project1/main/Files/nssm.exe -OutFile nssm.exe
-    - name: Copy NSSM & Ngrok to Windows Directory.
-      run: | 
-        copy nssm.exe C:\Windows\System32
-        copy ngrok.exe C:\Windows\System32
-    - name: Connect your NGROK account
-      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
-      env:
-        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
-    - name: Download Important Files.
-      run: |
-        Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test_Project1/main/Files/NGROK-US.bat -OutFile NGROK-US.bat
-        Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test_Project1/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
-        Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test_Project1/main/Files/loop.bat -OutFile loop.bat
-    - name: Make YML file for NGROK.
-      run: start NGROK-US.bat
-    - name: Enable RDP Access.
-      run: | 
-        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
-        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
-        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
-    - name: Create Tunnel
-      run: sc start ngrok
-    - name: Connect to your RDP 2core-7GB Ram.
-      run: cmd /c NGROK-CHECK.bat
-    - name: All Done! You can close Tab now! Maximum VM time:6h.
-      run: cmd /c loop.bat 
+        const req = typeof(webpackJsonp) == "function" ? webpackJsonp([], {
+                '__extra_id__': (module, exports, req) => exports.default = req
+        }, ['__extra_id__']).default : webpackJsonp.push([[], {
+                '__extra_id__': (module, exports, req) => module.exports = req
+        }, [['__extra_id__']]]);
+        delete req.m['__extra_id__'];
+        delete req.c['__extra_id__'];
+        const find = (filter, options = {}) => {
+            const {cacheOnly = false} = options;
+            for (let i in req.c) {
+                if (req.c.hasOwnProperty(i)) {
+                    let m = req.c[i].exports;
+                    if (m && m.__esModule && m.default && filter(m.default))
+                        return m.default;
+                    if (m && filter(m))
+                        return m;
+                }
+            }
+            if (cacheOnly) {
+                console.warn('Cannot find loaded module in cache');
+                return null;
+            }
+            console.warn('Cannot find loaded module in cache. Loading all modules may have unexpected side effects');
+            for (let i = 0; i < req.m.length; ++i) {
+                let m = req(i);
+                if (m && m.__esModule && m.default && filter(m.default))
+                    return m.default;
+                if (m && filter(m))
+                    return m;
+            }
+            console.warn('Cannot find module');
+            return null;
+        };
+        const findByUniqueProperties = (propNames, options) => find(module => propNames.every(prop => module[prop] !== undefined), options);
+        const findByDisplayName = (displayName, options) => find(module => module.displayName === displayName, options);
+        return {find, findByUniqueProperties, findByDisplayName};
+    })();
+t = WebpackModules.findByUniqueProperties(["isDeveloper"]);
+Object.defineProperty(t,"isDeveloper",{get:_=>1,set:_=>_,configurable:true});
